GET http://localhost:5000/api/phones HTTP/1.1

###
GET http://localhost:5000/api/phones/3 HTTP/1.1

###

POST http://localhost:5000/api/phones HTTP/1.1
Content-Type: application/json

{   
    "brandId": 6,
    "model": "Xreria 1",
    "manufacturedAt": 2019,
    "ramSize": 6,
    "processor": "Snapdragon 855",
    "screenDiagonal": 6.5,
    "isHavingNFC": true
}

###

DELETE http://localhost:5000/api/phones/1 HTTP/1.1

###

PUT http://localhost:5000/api/phones/4 HTTP/1.1
Content-Type: application/json

{
    "processor": "Snapdragon 845"
}

###

PUT http://localhost:5000/api/phones/6 HTTP/1.1
Content-Type: application/json

{   
    "brand": "Xiaomi",
    "model": "Redmi Note 10 64Gb",
    "manufacturedAt": 2021,
    "ramSize": 4,
    "processor": "Snapdragon 678",
    "screenDiagonal": 6.43,
    "isHavingNFC": false
}

###

GET http://localhost:5000/api/brands HTTP/1.1

###
GET http://localhost:5000/api/brands/xiaomi HTTP/1.1